INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Sodium, Na mg', '2300.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Iron, Fe mg', '45.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Calcium, Ca mg', '2500.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Phosphorus, P mg', '4000.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Zinc, Zn mg', '40.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Copper, Cu mg', '10.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Selenium, Se µg', '400.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Manganese, Mn mg', '11.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Fluoride, F µg', '10000.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Vitamin A, RAE µg', '3000.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Vitamin D (D2 + D3), International Units IU', '5000.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Vitamin D (D2 + D3) µg', '125.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Vitamin E (alpha-tocopherol) mg', '1000.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Vitamin B-6 mg', '100.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Folic acid µg', '1000.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Niacin mg', '35.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Choline, total mg', '3500.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Cholesterol mg', '200.0');
INSERT INTO "main"."UL" ("user_id", "nutrient", "value") VALUES (xx, 'Fatty acids, total saturated g', '22.0');