INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Fiber, total dietary g', '30.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Calcium, Ca mg', '1000.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Iron, Fe mg', '15.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Magnesium, Mg mg', '400.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Phosphorus, P mg', '700.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Potassium, K mg', '4700.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Zinc, Zn mg', '11.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Copper, Cu mg', '0.9');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Selenium, Se µg', '55.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Vitamin C, total ascorbic acid mg', '100.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Thiamin mg', '1.2');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Riboflavin mg', '1.3');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Niacin mg', '16.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Pantothenic acid mg', '5.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Vitamin B-6 mg', '1.5');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Folate, total µg', '400.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Vitamin B-12 µg', '2.4');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Choline, total mg', '550.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Vitamin E (alpha-tocopherol) mg', '15.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Vitamin K, total µg', '100.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Vitamin A, RAE µg', '900.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Vitamin D (D2 + D3), International Units IU', '600.0');
INSERT INTO "main"."RDA" ("user_id", "nutrient", "value") VALUES (xx, 'Vitamin D (D2 + D3) µg', '15.0');